---
apiVersion: v1
kind: Namespace
metadata:
  name:  prod
  labels:
    name: prod
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: res-quota
  namespace: prod
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 5Gi
    limits.cpu: "5"
    limits.memory: 6Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod
  annotations:
    kubernetes.io/change-cause: "deploy with res-quota"
  name: deploy-quota
  labels:
    app: deploy-quota
spec:
  #revisionHistoryLimit: 2
  replicas: 2
  selector:
    matchLabels:
      app: deploy-quota
  template:
    metadata:
      labels:
        app: deploy-quota
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: "600Mi"
            cpu: "3"
          requests:
            memory: "500Mi"
            cpu: "2"
---