apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Pagina Web con Servicio"
  name: deploy-np
  labels:
    app: deploy-np-front
spec:
  #revisionHistoryLimit: 2
  replicas: 3
  selector:
    matchLabels:
      app: deploy-np-front
  template:
    metadata:
      labels:
        app: deploy-np-front
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
---
apiVersion: v1
kind: Service
metadata:
  name: svc-np
  labels:
    app: deploy-np-front
spec:
  type: NodePort
  selector:
    app: deploy-np-front
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80