---
apiVersion: v1
kind: Namespace
metadata:
  name:  dev
  labels:
    name: dev
---   
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-cm
  namespace: dev
spec:
  limits:
  - default:
      memory: 1024Mi
      cpu: "1"
    defaultRequest:
      memory: 512Mi
      cpu: "0.5"
    type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: tempalte-pod
  namespace: dev  
spec:
  containers:
    - name: web-template
      image: nginx:alpine