---
apiVersion: v1
kind: Namespace
metadata:
  name:  qa
  labels:
    name: qa
---   
apiVersion: v1
kind: LimitRange
metadata:
  name: min-max-limit
  namespace: qa
spec:
  limits:
  - max:
      memory: 1Gi
      cpu: "1"
    min:
      memory: 200Mi
      cpu: "0.3"
    type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: tempalte-pod
  namespace: qa  
spec:
  containers:
    - name: web-template
      image: nginx:alpine
      resources:
        limits:
          memory: 200Mi
          cpu:  "0.2"
        requests:
          memory: 500Mi
          cpu:  "0.5"
