apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "frontend servicio web go"
  name: k8s-frontend-go
  labels:
    app: frontend
spec:
  #revisionHistoryLimit: 2
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: registry.gitlab.com/miguelrojas/ingarch-k8s/frontend:latest
      imagePullSecrets:
      - name: regcred
      dnsPolicy: ClusterFirstWithHostNet
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-frontend-go
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80